### ISSUE TITLE
missing docstring for js-react-redux-yasnippets-want-semicolon breaks yasnippet loading

### ISSUE THREAD

**Issue by AloisJanicek** [sooqua/js-react-redux-yasnippets#1]
Hi, your recent update https://github.com/sooqua/js-react-redux-yasnippets/commit/33403d73d50b03e0d3a4e66ce0a0b886c8082efe breaks my whole emacs setup when yasnippet is loaded. I tracked the issue to the missing docstring of `js-react-redux-yasnippets-want-semicolon` .
On emacs 27 docstring is mandatory `(defcustom SYMBOL STANDARD DOC &rest ARGS)` (maybe it is optional on other versions of emacs).
Adding string as a third argument fixed yasnippet loading for me.

**Comment by sooqua** [comment]
Whoops. It's fixed now. Thanks for bringing this to my attention!
